// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjTOxa2nCCAxNJFbw2qp_hJa-GnU4oohE',
    appId: '1:458345126735:web:90eb4dbc22a457efcd433a',
    messagingSenderId: '458345126735',
    projectId: 'crowncreation-359d1',
    authDomain: 'crowncreation-359d1.firebaseapp.com',
    storageBucket: 'crowncreation-359d1.firebasestorage.app',
    measurementId: 'G-X54P3G2R79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBISUjomNqZLNGLey7vX_NU5oXzTKZuMbk',
    appId: '1:458345126735:android:c3ca3d6191c26299cd433a',
    messagingSenderId: '458345126735',
    projectId: 'crowncreation-359d1',
    storageBucket: 'crowncreation-359d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDklL-mG_MV45h8COR0NdALOch-Ey__eIQ',
    appId: '1:458345126735:ios:52fcfad68815f5e0cd433a',
    messagingSenderId: '458345126735',
    projectId: 'crowncreation-359d1',
    storageBucket: 'crowncreation-359d1.firebasestorage.app',
    androidClientId: '458345126735-q48nng7plb28dbors1ucaqc79ql29ebv.apps.googleusercontent.com',
    iosClientId: '458345126735-lljt2399q7ckle4fn18b0i60mlugvk5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.crowncreation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDklL-mG_MV45h8COR0NdALOch-Ey__eIQ',
    appId: '1:458345126735:ios:52fcfad68815f5e0cd433a',
    messagingSenderId: '458345126735',
    projectId: 'crowncreation-359d1',
    storageBucket: 'crowncreation-359d1.firebasestorage.app',
    androidClientId: '458345126735-q48nng7plb28dbors1ucaqc79ql29ebv.apps.googleusercontent.com',
    iosClientId: '458345126735-lljt2399q7ckle4fn18b0i60mlugvk5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.crowncreation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjTOxa2nCCAxNJFbw2qp_hJa-GnU4oohE',
    appId: '1:458345126735:web:d94d08aafc9e3c77cd433a',
    messagingSenderId: '458345126735',
    projectId: 'crowncreation-359d1',
    authDomain: 'crowncreation-359d1.firebaseapp.com',
    storageBucket: 'crowncreation-359d1.firebasestorage.app',
    measurementId: 'G-6PT10R71VH',
  );

}